[build]
  base = "/"
  command = "chmod +x build.sh && ./build.sh"
  publish = "staticfiles"

[build.environment]
  PYTHON_VERSION = "3.11.0"
  NODE_VERSION = "18.17.0"  # More specific Node version
  DJANGO_SETTINGS_MODULE = "crm.settings"

[context.production.environment]
  DEBUG = "0"
  PYTHONPATH = "."

[context.deploy-preview]
  command = """
    python -m pip install -r requirements.txt &&
    python manage.py collectstatic --noinput
  """

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  framework = "#custom"
  command = "python manage.py runserver"
  port = 8000
  targetPort = 8000
  publish = "staticfiles"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
