[build]
  base = "./"
  command = """
    mkdir -p /opt/build/cache
    curl -sSL https://install.python-poetry.org | python3 -
    apt-get update && apt-get install -y python3.9 python3.9-dev python3-pip build-essential
    python3.9 -m pip install --upgrade pip
    pip install -r requirements.txt
    python3.9 manage.py collectstatic --noinput
    python3.9 manage.py migrate --noinput
  """
  publish = "staticfiles"

[build.environment]
  NODE_VERSION = "18.17.0"
  PYTHON_VERSION = "3.9"
  DJANGO_SETTINGS_MODULE = "crm.settings"
  PYTHONPATH = "."
  DEBUG = "0"
  SECRET_KEY = "${SECRET_KEY}"
  NETLIFY_SITE_NAME = "crm-elkhawaga"

[context.production.environment]
  DEBUG = "0"

[[plugins]]
  package = "@netlify/plugin-python"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/media/*" 
  to = "/media/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net;
      style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net;
      img-src 'self' data: https:;
      font-src 'self' https://cdn.jsdelivr.net;
    """
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
