[build]
  base = "./"
  command = """
    python3 -m pip install --upgrade pip
    pip install -r requirements.txt
    python3 manage.py collectstatic --noinput
  """
  publish = "staticfiles"

[build.environment]
  PYTHON_VERSION = "3.9"
  DJANGO_SETTINGS_MODULE = "crm.settings"
  PYTHONPATH = "."
  DEBUG = "0"

[[plugins]]
  package = "@netlify/plugin-python"
  [plugins.inputs]
    pythonVersion = "3.9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
