[build]
  base = ""
  publish = "staticfiles"
  command = "pip install -r requirements.txt && python manage.py collectstatic --noinput"

[build.environment]
  PYTHON_VERSION = "3.8.12"
  DJANGO_SETTINGS_MODULE = "crm.settings"

[[plugins]]
  package = "@netlify/plugin-django"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
