[build]
  base = "./"
  command = """
    chmod +x build.sh && ./build.sh
    cd netlify/functions && pip install -r requirements.txt
  """
  publish = "staticfiles"
  functions = "netlify/functions"
  ignore = "git diff --quiet HEAD^ HEAD netlify/"

[build.environment]
  PYTHON_VERSION = "3.9"
  DJANGO_SETTINGS_MODULE = "crm.settings"
  PYTHONPATH = "."
  DEBUG = "0"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = [
    "crm/**/*",
    "templates/**/*",
    "staticfiles/**/*",
    "netlify/functions/requirements.txt",
    "netlify/functions/runtime.txt"
  ]

[functions.django]
  external_node_modules = []
  included_files = ["**/*"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/django/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/django"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
