[build]
  command = """
    python -m pip install --upgrade pip &&
    pip install -r requirements.txt &&
    python manage.py collectstatic --noinput
  """
  publish = "staticfiles"

[build.environment]
  PYTHON_VERSION = "3.11.0"
  DJANGO_SETTINGS_MODULE = "crm.settings"

[context.production.environment]
  DJANGO_SETTINGS_MODULE = "crm.settings"
  PYTHONPATH = "."
  DEBUG = "0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
