[build]
  base = "./"
  command = "chmod +x build.sh && ./build.sh"
  publish = "staticfiles"
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.9"
  DJANGO_SETTINGS_MODULE = "crm.settings"
  PYTHONPATH = "."
  DEBUG = "0"

[functions]
  external_node_modules = []
  included_files = ["crm/**/*", "templates/**/*", "staticfiles/**/*"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/django/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/django"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
