[build]
  command = """
    python -m pip install -r requirements-dev.txt &&
    python manage.py collectstatic --noinput
  """
  publish = "staticfiles"

[build.environment]
  PYTHON_VERSION = "3.11.0"
  DJANGO_SETTINGS_MODULE = "crm.settings"
  PIP_NO_BINARY = "psycopg2-binary"

[context.production.environment]
  DJANGO_SETTINGS_MODULE = "crm.settings"
  PYTHONPATH = "."
  DEBUG = "0"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';"
