[build]
  base = "./"
  command = """
    python3 -m pip install --upgrade pip
    pip install -r requirements.txt
    python3 manage.py collectstatic --noinput
    python3 manage.py migrate --noinput
  """
  publish = "staticfiles"

[build.environment]
  PYTHON_VERSION = "3.9"
  DJANGO_SETTINGS_MODULE = "crm.settings"
  PYTHONPATH = "."
  DEBUG = "0"

[[plugins]]
  package = "@netlify/plugin-python"
  [plugins.inputs]
    pythonVersion = "3.9"
