# Generated by Django 5.2 on 2025-04-13 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_alter_productionorder_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'جاري التصنيع'), ('completed', 'مكتمل'), ('stalled', 'متعطل'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.CreateModel(
            name='ProductionIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المشكلة')),
                ('description', models.TextField(verbose_name='وصف المشكلة')),
                ('severity', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('critical', 'حرجة')], default='medium', max_length=20, verbose_name='خطورة المشكلة')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإبلاغ')),
                ('resolved', models.BooleanField(default=False, verbose_name='تم الحل')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='ملاحظات الحل')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='factory.productionorder', verbose_name='أمر الإنتاج')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_issues', to=settings.AUTH_USER_MODEL, verbose_name='تم الإبلاغ بواسطة')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_issues', to=settings.AUTH_USER_MODEL, verbose_name='تم الحل بواسطة')),
            ],
            options={
                'verbose_name': 'مشكلة إنتاج',
                'verbose_name_plural': 'مشاكل الإنتاج',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.DeleteModel(
            name='QualityCheck',
        ),
    ]
