# Generated by Django 5.2 on 2025-04-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_branch_delete_companyinfo_remove_user_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_main_branch',
            field=models.BooleanField(default=False, verbose_name='فرع رئيسي'),
        ),
    ]
