# Generated by Django 5.2 on 2025-04-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_branch_is_main_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القسم')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود القسم')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('icon', models.CharField(default='fas fa-building', max_length=50, verbose_name='أيقونة')),
                ('url_name', models.CharField(help_text='اسم URL للقسم في نظام التوجيه', max_length=100, verbose_name='اسم URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='الأقسام التي يمكن للمستخدم الوصول إليها', related_name='users', to='accounts.department', verbose_name='الأقسام'),
        ),
    ]
