# Generated by Django 5.2 on 2025-04-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الشركة')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='شعار الشركة')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('website', models.URLField(blank=True, verbose_name='الموقع الإلكتروني')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='الرقم الضريبي')),
                ('commercial_register', models.CharField(blank=True, max_length=50, verbose_name='السجل التجاري')),
                ('facebook', models.URLField(blank=True, verbose_name='فيسبوك')),
                ('twitter', models.URLField(blank=True, verbose_name='تويتر')),
                ('instagram', models.URLField(blank=True, verbose_name='انستغرام')),
                ('linkedin', models.URLField(blank=True, verbose_name='لينكد إن')),
                ('about', models.TextField(blank=True, verbose_name='نبذة عن الشركة')),
                ('vision', models.TextField(blank=True, verbose_name='رؤية الشركة')),
                ('mission', models.TextField(blank=True, verbose_name='رسالة الشركة')),
                ('primary_color', models.CharField(default='#007bff', max_length=7, verbose_name='اللون الرئيسي')),
                ('secondary_color', models.CharField(default='#6c757d', max_length=7, verbose_name='اللون الثانوي')),
                ('accent_color', models.CharField(default='#28a745', max_length=7, verbose_name='لون التمييز')),
            ],
            options={
                'verbose_name': 'معلومات الشركة',
                'verbose_name_plural': 'معلومات الشركة',
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_type', models.CharField(choices=[('order', 'نموذج الطلب'), ('customer', 'نموذج العميل'), ('production', 'نموذج الإنتاج'), ('inspection', 'نموذج المعاينة'), ('installation', 'نموذج التركيب')], max_length=20, verbose_name='نوع النموذج')),
                ('field_name', models.CharField(max_length=100, verbose_name='اسم الحقل')),
                ('field_label', models.CharField(max_length=255, verbose_name='عنوان الحقل')),
                ('field_type', models.CharField(choices=[('text', 'نص'), ('number', 'رقم'), ('date', 'تاريخ'), ('datetime', 'تاريخ ووقت'), ('select', 'قائمة اختيار'), ('checkbox', 'مربع اختيار'), ('radio', 'زر راديو'), ('textarea', 'منطقة نص'), ('file', 'ملف'), ('image', 'صورة')], max_length=20, verbose_name='نوع الحقل')),
                ('required', models.BooleanField(default=False, verbose_name='مطلوب')),
                ('enabled', models.BooleanField(default=True, verbose_name='مفعل')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('choices', models.TextField(blank=True, help_text='أدخل الخيارات مفصولة بفاصلة', verbose_name='الخيارات')),
                ('min_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='الحد الأدنى للطول')),
                ('max_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='الحد الأقصى للطول')),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='الحد الأدنى للقيمة')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='الحد الأقصى للقيمة')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='نص المساعدة')),
                ('default_value', models.CharField(blank=True, max_length=255, verbose_name='القيمة الافتراضية')),
            ],
            options={
                'verbose_name': 'حقل نموذج',
                'verbose_name_plural': 'حقول النماذج',
                'ordering': ['form_type', 'order'],
                'unique_together': {('form_type', 'field_name')},
            },
        ),
    ]
