# Generated by Django 4.2.20 on 2025-04-15 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_companyinfo_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'جلسة المستخدم',
                'verbose_name_plural': 'جلسات المستخدمين',
            },
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'فرع', 'verbose_name_plural': 'الفروع'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'قسم', 'verbose_name_plural': 'الأقسام'},
        ),
        migrations.RemoveField(
            model_name='branch',
            name='code',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='about',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='accent_color',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='secondary_color',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='vision',
        ),
        migrations.RemoveField(
            model_name='department',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='department',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='department',
            name='order',
        ),
        migrations.RemoveField(
            model_name='department',
            name='url_name',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='read_by',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='social_links',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_users',
            field=models.ManyToManyField(blank=True, related_name='received_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='is_main_branch',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='commercial_register',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.branch'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.branch'),
        ),
        migrations.AlterField(
            model_name='user',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='users', to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
