# Generated by Django 4.2.20 on 2025-04-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_branch_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='developer',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='المطور'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='release_date',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='تاريخ الإطلاق'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='version',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='إصدار النظام'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='working_hours',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ساعات العمل'),
        ),
    ]
