# Generated by Django 4.2.20 on 2025-04-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_populate_department_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='العنوان'),
        ),
    ]
