# Generated by Django 4.2.20 on 2025-04-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20250415_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='الترتيب'),
        ),
    ]
