# Generated by Django 4.2.20 on 2025-04-15 18:27

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20250415_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='content_type_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
