# Generated by Django 4.2.20 on 2025-04-15 18:30

from django.db import migrations, models
from django.conf import settings
from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20250415_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='read_notifications', to=settings.AUTH_USER_MODEL, verbose_name='قرأت بواسطة'),
        ),
    ]
