# Generated by Django 5.2 on 2025-04-16 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_companyinfo_developer_companyinfo_release_date_and_more'),
        ('accounts', '0017_remove_user_session'),
    ]

    operations = [
    ]
