# Generated by Django 5.2 on 2025-04-14 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_companyinfo_description'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, verbose_name='رقم الدفعة')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('manufacturing_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التصنيع')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الصلاحية')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر التكلفة')),
                ('barcode', models.CharField(blank=True, max_length=100, verbose_name='الباركود')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'دفعة منتج',
                'verbose_name_plural': 'دفعات المنتجات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('count', 'جرد'), ('damage', 'تلف'), ('loss', 'فقدان'), ('return', 'مرتجع'), ('other', 'أخرى')], max_length=10, verbose_name='نوع التسوية')),
                ('quantity_before', models.PositiveIntegerField(verbose_name='الكمية قبل التسوية')),
                ('quantity_after', models.PositiveIntegerField(verbose_name='الكمية بعد التسوية')),
                ('reason', models.TextField(verbose_name='سبب التسوية')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسوية')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_adjustments', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory.product', verbose_name='المنتج')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='inventory.productbatch', verbose_name='الدفعة')),
            ],
            options={
                'verbose_name': 'تسوية مخزون',
                'verbose_name_plural': 'تسويات المخزون',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الوحدة')),
                ('received_quantity', models.PositiveIntegerField(default=0, verbose_name='الكمية المستلمة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_items', to='inventory.product', verbose_name='المنتج')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaseorder', verbose_name='طلب الشراء')),
            ],
            options={
                'verbose_name': 'عنصر طلب شراء',
                'verbose_name_plural': 'عناصر طلبات الشراء',
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_stock', 'مخزون منخفض'), ('out_of_stock', 'نفاد المخزون'), ('expiry', 'قرب انتهاء الصلاحية')], max_length=20, verbose_name='نوع التنبيه')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('in_progress', 'قيد المعالجة'), ('resolved', 'تم الحل'), ('ignored', 'تم التجاهل')], default='new', max_length=20, verbose_name='الحالة')),
                ('message', models.TextField(verbose_name='رسالة التنبيه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='inventory.product', verbose_name='المنتج')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_stock_alerts', to=settings.AUTH_USER_MODEL, verbose_name='تم الحل بواسطة')),
            ],
            options={
                'verbose_name': 'تنبيه مخزون',
                'verbose_name_plural': 'تنبيهات المخزون',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المخزن')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود المخزن')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='accounts.branch', verbose_name='الفرع')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='المدير المسؤول')),
            ],
            options={
                'verbose_name': 'مخزن',
                'verbose_name_plural': 'المخازن',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='inventory.warehouse', verbose_name='المخزن المستلم'),
        ),
        migrations.CreateModel(
            name='WarehouseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الموقع')),
                ('code', models.CharField(max_length=20, verbose_name='كود الموقع')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory.warehouse', verbose_name='المخزن')),
            ],
            options={
                'verbose_name': 'موقع في المخزن',
                'verbose_name_plural': 'مواقع المخزن',
                'ordering': ['warehouse', 'name'],
                'unique_together': {('warehouse', 'code')},
            },
        ),
        migrations.AddField(
            model_name='productbatch',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_batches', to='inventory.warehouselocation', verbose_name='الموقع'),
        ),
        migrations.AlterUniqueTogether(
            name='productbatch',
            unique_together={('product', 'batch_number')},
        ),
    ]
