# Generated by Django 5.2 on 2025-04-09 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_order_created_by_remove_order_customer_and_more'),
        ('factory', '0002_alter_productionorder_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
