# Generated by Django 5.2 on 2025-04-10 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_branch_delete_companyinfo_remove_user_address_and_more'),
        ('customers', '0003_delete_order_delete_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'verbose_name': 'عميل', 'verbose_name_plural': 'سجل العملاء'},
        ),
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='accounts.branch', verbose_name='الفرع'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='كود العميل'),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('blocked', 'محظور')], default='active', max_length=10, verbose_name='الحالة'),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
    ]
