# Generated by Django 4.2.20 on 2025-04-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_import_export', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importexportlog',
            name='is_multi_sheet',
            field=models.BooleanField(default=False, verbose_name='ملف متعدد الصفحات'),
        ),
    ]
