# Generated by Django 5.2 on 2025-04-10 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_branch_delete_companyinfo_remove_user_address_and_more'),
        ('customers', '0004_alter_customer_options_customer_branch_customer_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='رقم العقد')),
                ('request_date', models.DateField(verbose_name='تاريخ طلب المعاينة')),
                ('scheduled_date', models.DateField(verbose_name='تاريخ تنفيذ المعاينة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'مكتملة'), ('cancelled', 'ملغية')], default='pending', max_length=10, verbose_name='الحالة')),
                ('result', models.CharField(blank=True, choices=[('passed', 'ناجحة'), ('failed', 'غير مجدية')], max_length=10, null=True, verbose_name='النتيجة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='accounts.branch', verbose_name='الفرع')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections_created', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='customers.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'معاينة',
                'verbose_name_plural': 'المعاينات',
                'ordering': ['-request_date'],
            },
        ),
    ]
