# Generated by Django 4.2.20 on 2025-04-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_inspectionevaluation_inspectionnotification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='contract_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رقم العقد'),
        ),
    ]
