# Generated by Django 5.2 on 2025-04-13 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_branch_is_main_branch'),
        ('inventory', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('goods', 'سلع'), ('services', 'خدمات')], max_length=10, verbose_name='نوع الطلب')),
                ('goods_type', models.CharField(blank=True, choices=[('accessories', 'اكسسوار'), ('fabric', 'قماش')], max_length=15, null=True, verbose_name='نوع السلعة')),
                ('service_type', models.CharField(blank=True, choices=[('inspection', 'معاينة'), ('tailoring', 'تفصيل'), ('installation', 'تركيب'), ('transport', 'نقل')], max_length=15, null=True, verbose_name='نوع الخدمة')),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الفاتورة')),
                ('contract_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم العقد')),
                ('payment_verified', models.BooleanField(default=False, verbose_name='تم التحقق من السداد')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extended_orders', to='accounts.branch', verbose_name='الفرع')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extended_info', to='orders.order', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'معلومات إضافية للطلب',
                'verbose_name_plural': 'معلومات إضافية للطلبات',
            },
        ),
        migrations.CreateModel(
            name='AccessoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accessory_items', to='inventory.product', verbose_name='المنتج')),
                ('extended_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_items', to='orders.extendedorder', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'عنصر اكسسوار',
                'verbose_name_plural': 'عناصر الاكسسوارات',
            },
        ),
        migrations.CreateModel(
            name='FabricOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('cutting', 'قيد التقطيع'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='pending', max_length=10, verbose_name='الحالة')),
                ('sent_to_warehouse', models.BooleanField(default=False, verbose_name='تم إرسال للمخزن')),
                ('cutting_completed', models.BooleanField(default=False, verbose_name='تم التقطيع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('extended_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fabric_order', to='orders.extendedorder', verbose_name='الطلب')),
                ('fabric_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fabric_orders', to='inventory.product', verbose_name='نوع القماش')),
            ],
            options={
                'verbose_name': 'طلب قماش',
                'verbose_name_plural': 'طلبات الأقمشة',
            },
        ),
    ]
