# Generated by Django 4.2.20 on 2025-04-14 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_companyinfo_description'),
        ('orders', '0002_extendedorder_accessoryitem_fabricorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.branch', verbose_name='الفرع'),
        ),
        migrations.AddField(
            model_name='order',
            name='contract_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم العقد'),
        ),
        migrations.AddField(
            model_name='order',
            name='goods_type',
            field=models.CharField(choices=[('fabric', 'أقمشة'), ('accessories', 'إكسسوارات'), ('both', 'كلاهما')], default='both', max_length=20, verbose_name='نوع البضاعة'),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الفاتورة'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('regular', 'عادي'), ('urgent', 'عاجل')], default='regular', max_length=10, verbose_name='نوع الطلب'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_verified',
            field=models.BooleanField(default=False, verbose_name='تم التحقق من السداد'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_type',
            field=models.CharField(blank=True, choices=[('inspection', 'معاينة'), ('tailoring', 'تفصيل'), ('installation', 'تركيب'), ('transport', 'نقل')], max_length=15, null=True, verbose_name='نوع الخدمة'),
        ),
    ]
