# Generated by Django 4.2.20 on 2025-04-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_branch_order_contract_number_order_goods_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='goods_type',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('product', 'منتج'), ('service', 'خدمة')], max_length=10, verbose_name='نوع الطلب'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_type',
            field=models.CharField(blank=True, choices=[('installation', 'تركيب'), ('inspection', 'معاينة'), ('transport', 'نقل')], max_length=15, null=True, verbose_name='نوع الخدمة'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('normal', 'عادي'), ('vip', 'VIP')], default='normal', max_length=20, verbose_name='حالة الطلب'),
        ),
    ]
