# Generated by Django 4.2.20 on 2025-04-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_service_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, null=True, verbose_name='عنوان التسليم'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('home', 'توصيل للمنزل'), ('branch', 'استلام من الفرع')], default='branch', max_length=10, verbose_name='نوع التسليم'),
        ),
    ]
