# Generated by Django 4.2.20 on 2025-04-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_delivery_address_order_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='goods_type',
            field=models.CharField(choices=[('fabric', 'أقمشة'), ('accessories', 'إكسسوارات'), ('both', 'كلاهما')], default='both', max_length=20, verbose_name='نوع البضاعة'),
        ),
    ]
