# Generated by Django 4.2.20 on 2025-04-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20250415_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_type',
            field=models.CharField(blank=True, choices=[('inspection', 'معاينة'), ('tailoring', 'تفصيل'), ('installation', 'تركيب'), ('transport', 'نقل')], max_length=15, null=True, verbose_name='نوع الخدمة'),
        ),
    ]
