# Generated by Django 5.2 on 2025-04-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20250415_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='goods_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='service_type',
        ),
    ]
